### PR TITLE
Additions(Visually & into API)

### PR DESCRIPTION
**Pull request by burpingdog1**
Adds prefix to identifier

Added:
Command to set specified slot identifiers size
API method to set size

(get size is in v1.0.3 but added it in to get it to work)

### CODE REVIEW

**Comment by Extegral** [comment]
I'd like to say, this prefix instills doubt in me. Especially colors.

**Comment by TheIllusiveC4** [comment]
@Extegral Could you elaborate on your thoughts? What is the cause for skepticism?

**Comment by Extegral** [comment]
On a second thought, wording is actually fine. However, it may be my personal opinion, but orange color for "Slot:" and light gray for slot type don't seem to look so good.

I would have offered something like orange and yellow, or maybe orange and light purple.

**Comment by burpingdog1** [comment]
image
Thats with orange

**Pull request merged**
